// services.js
// the list. edit freely — add, remove, reorder.
// label must be lowercase, no spaces (it becomes a github label)

const GITHUB_REPO = ''; // 'your-username/netpulse'

const SERVICES = [
  // ── Social & Communication ──────────────────────────────────────────────
  { id:1,   name:'Discord',         icon:'◈', color:'#5865F2', category:'social',    label:'discord'          },
  { id:2,   name:'Slack',           icon:'◉', color:'#4A154B', category:'social',    label:'slack'            },
  { id:3,   name:'Twitter / X',     icon:'✕', color:'#000000', category:'social',    label:'twitter-x'        },
  { id:4,   name:'Instagram',       icon:'⬡', color:'#E1306C', category:'social',    label:'instagram'        },
  { id:5,   name:'Facebook',        icon:'◧', color:'#1877F2', category:'social',    label:'facebook'         },
  { id:6,   name:'WhatsApp',        icon:'◎', color:'#25D366', category:'social',    label:'whatsapp'         },
  { id:7,   name:'Telegram',        icon:'▶', color:'#2AABEE', category:'social',    label:'telegram'         },
  { id:8,   name:'Reddit',          icon:'◕', color:'#FF4500', category:'social',    label:'reddit'           },
  { id:9,   name:'LinkedIn',        icon:'▣', color:'#0A66C2', category:'social',    label:'linkedin'         },
  { id:10,  name:'Snapchat',        icon:'⬢', color:'#FFFC00', category:'social',    label:'snapchat'         },
  { id:11,  name:'TikTok',          icon:'◈', color:'#010101', category:'social',    label:'tiktok'           },
  { id:12,  name:'Pinterest',       icon:'◉', color:'#E60023', category:'social',    label:'pinterest'        },
  { id:13,  name:'Mastodon',        icon:'⬡', color:'#6364FF', category:'social',    label:'mastodon'         },
  { id:14,  name:'Twitch',          icon:'◧', color:'#9146FF', category:'streaming', label:'twitch'           },
  { id:15,  name:'Zoom',            icon:'◎', color:'#2D8CFF', category:'social',    label:'zoom'             },
  { id:16,  name:'Teams',           icon:'▶', color:'#6264A7', category:'social',    label:'teams'            },

  // ── Streaming & Media ───────────────────────────────────────────────────
  { id:17,  name:'YouTube',         icon:'▶', color:'#FF0000', category:'streaming', label:'youtube'          },
  { id:18,  name:'Netflix',         icon:'◉', color:'#E50914', category:'streaming', label:'netflix'          },
  { id:19,  name:'Spotify',         icon:'◎', color:'#1DB954', category:'streaming', label:'spotify'          },
  { id:20,  name:'Disney+',         icon:'▣', color:'#113CCF', category:'streaming', label:'disney-plus'      },
  { id:21,  name:'Apple Music',     icon:'◈', color:'#FA243C', category:'streaming', label:'apple-music'      },
  { id:22,  name:'SoundCloud',      icon:'⬢', color:'#FF5500', category:'streaming', label:'soundcloud'       },
  { id:23,  name:'Hulu',            icon:'◕', color:'#1CE783', category:'streaming', label:'hulu'             },
  { id:24,  name:'HBO Max',         icon:'⬡', color:'#B535F6', category:'streaming', label:'hbo-max'          },
  { id:25,  name:'Amazon Prime',    icon:'◧', color:'#00A8E1', category:'streaming', label:'amazon-prime'     },
  { id:26,  name:'Apple TV+',       icon:'◈', color:'#000000', category:'streaming', label:'apple-tv'         },
  { id:27,  name:'Peacock',         icon:'◉', color:'#FF6D00', category:'streaming', label:'peacock'          },
  { id:28,  name:'Deezer',          icon:'◎', color:'#FEAA2D', category:'streaming', label:'deezer'           },
  { id:29,  name:'Plex',            icon:'▶', color:'#E5A00D', category:'streaming', label:'plex'             },

  // ── Gaming ──────────────────────────────────────────────────────────────
  { id:30,  name:'Steam',           icon:'⊕', color:'#1b2838', category:'gaming',    label:'steam'            },
  { id:31,  name:'PlayStation',     icon:'◈', color:'#003087', category:'gaming',    label:'playstation'      },
  { id:32,  name:'Xbox',            icon:'◉', color:'#107C10', category:'gaming',    label:'xbox'             },
  { id:33,  name:'Roblox',          icon:'◧', color:'#E8081B', category:'gaming',    label:'roblox'           },
  { id:34,  name:'Epic Games',      icon:'◎', color:'#2F2F2F', category:'gaming',    label:'epic-games'       },
  { id:35,  name:'Riot Games',      icon:'▣', color:'#D73422', category:'gaming',    label:'riot-games'       },
  { id:36,  name:'Battle.net',      icon:'⬢', color:'#009AE4', category:'gaming',    label:'battle-net'       },
  { id:37,  name:'EA / Origin',     icon:'◕', color:'#F4821F', category:'gaming',    label:'ea-origin'        },
  { id:38,  name:'Nintendo',        icon:'◈', color:'#E60012', category:'gaming',    label:'nintendo'         },
  { id:39,  name:'Minecraft',       icon:'◉', color:'#62B47A', category:'gaming',    label:'minecraft'        },
  { id:40,  name:'Ubisoft',         icon:'◎', color:'#0070FF', category:'gaming',    label:'ubisoft'          },
  { id:41,  name:'GOG',             icon:'▶', color:'#86328A', category:'gaming',    label:'gog'              },

  // ── Cloud & Infrastructure ───────────────────────────────────────────────
  { id:42,  name:'AWS',             icon:'⬢', color:'#FF9900', category:'cloud',     label:'aws'              },
  { id:43,  name:'Google Cloud',    icon:'◕', color:'#4285F4', category:'cloud',     label:'google-cloud'     },
  { id:44,  name:'Azure',           icon:'⬡', color:'#0078D4', category:'cloud',     label:'azure'            },
  { id:45,  name:'Cloudflare',      icon:'☁', color:'#F48120', category:'cloud',     label:'cloudflare'       },
  { id:46,  name:'Vercel',          icon:'▲', color:'#171717', category:'cloud',     label:'vercel'           },
  { id:47,  name:'Netlify',         icon:'◈', color:'#00C7B7', category:'cloud',     label:'netlify'          },
  { id:48,  name:'Heroku',          icon:'◉', color:'#430098', category:'cloud',     label:'heroku'           },
  { id:49,  name:'DigitalOcean',    icon:'◎', color:'#0080FF', category:'cloud',     label:'digitalocean'     },
  { id:50,  name:'Fastly',          icon:'▣', color:'#FF282D', category:'cloud',     label:'fastly'           },
  { id:51,  name:'Akamai',          icon:'⬢', color:'#009BDE', category:'cloud',     label:'akamai'           },
  { id:52,  name:'Render',          icon:'◕', color:'#46E3B7', category:'cloud',     label:'render'           },
  { id:53,  name:'Fly.io',          icon:'⬡', color:'#7B3FE4', category:'cloud',     label:'fly-io'           },
  { id:54,  name:'Railway',         icon:'◧', color:'#0B0D0E', category:'cloud',     label:'railway'          },

  // ── Developer Tools ──────────────────────────────────────────────────────
  { id:55,  name:'GitHub',          icon:'◉', color:'#24292f', category:'developer', label:'github'           },
  { id:56,  name:'GitLab',          icon:'◈', color:'#FC6D26', category:'developer', label:'gitlab'           },
  { id:57,  name:'Bitbucket',       icon:'◎', color:'#0052CC', category:'developer', label:'bitbucket'        },
  { id:58,  name:'npm',             icon:'▶', color:'#CB3837', category:'developer', label:'npm'              },
  { id:59,  name:'PyPI',            icon:'◕', color:'#3775A9', category:'developer', label:'pypi'             },
  { id:60,  name:'Docker Hub',      icon:'⬡', color:'#2496ED', category:'developer', label:'docker-hub'       },
  { id:61,  name:'Sentry',          icon:'◧', color:'#362D59', category:'developer', label:'sentry'           },
  { id:62,  name:'Datadog',         icon:'◈', color:'#632CA6', category:'developer', label:'datadog'          },
  { id:63,  name:'PagerDuty',       icon:'◉', color:'#06AC38', category:'developer', label:'pagerduty'        },
  { id:64,  name:'Jira',            icon:'◎', color:'#0052CC', category:'developer', label:'jira'             },
  { id:65,  name:'Confluence',      icon:'▣', color:'#172B4D', category:'developer', label:'confluence'       },
  { id:66,  name:'Linear',          icon:'◎', color:'#5E6AD2', category:'developer', label:'linear'           },
  { id:67,  name:'Notion',          icon:'▣', color:'#6B6B6B', category:'developer', label:'notion'           },
  { id:68,  name:'Figma',           icon:'⬢', color:'#F24E1E', category:'developer', label:'figma'            },
  { id:69,  name:'Supabase',        icon:'◕', color:'#3ECF8E', category:'developer', label:'supabase'         },
  { id:70,  name:'Firebase',        icon:'⬡', color:'#FFCA28', category:'developer', label:'firebase'         },
  { id:71,  name:'MongoDB Atlas',   icon:'◧', color:'#00ED64', category:'developer', label:'mongodb-atlas'    },
  { id:72,  name:'PlanetScale',     icon:'◈', color:'#000000', category:'developer', label:'planetscale'      },
  { id:73,  name:'Neon',            icon:'◉', color:'#00E699', category:'developer', label:'neon'             },
  { id:74,  name:'Postman',         icon:'◎', color:'#FF6C37', category:'developer', label:'postman'          },

  // ── AI Services ──────────────────────────────────────────────────────────
  { id:75,  name:'OpenAI',          icon:'◈', color:'#10A37F', category:'ai',        label:'openai'           },
  { id:76,  name:'Anthropic',       icon:'◉', color:'#D4A27E', category:'ai',        label:'anthropic'        },
  { id:77,  name:'Google Gemini',   icon:'◎', color:'#4285F4', category:'ai',        label:'google-gemini'    },
  { id:78,  name:'Midjourney',      icon:'▣', color:'#000000', category:'ai',        label:'midjourney'       },
  { id:79,  name:'Hugging Face',    icon:'⬢', color:'#FFD21E', category:'ai',        label:'hugging-face'     },
  { id:80,  name:'Replicate',       icon:'◕', color:'#171717', category:'ai',        label:'replicate'        },
  { id:81,  name:'Perplexity',      icon:'⬡', color:'#1FB8CD', category:'ai',        label:'perplexity'       },
  { id:82,  name:'Cursor',          icon:'◧', color:'#000000', category:'ai',        label:'cursor'           },

  // ── Finance & Payments ───────────────────────────────────────────────────
  { id:83,  name:'Stripe',          icon:'⬡', color:'#635BFF', category:'finance',   label:'stripe'           },
  { id:84,  name:'PayPal',          icon:'◈', color:'#003087', category:'finance',   label:'paypal'           },
  { id:85,  name:'Shopify',         icon:'◧', color:'#96BF48', category:'finance',   label:'shopify'          },
  { id:86,  name:'Square',          icon:'◉', color:'#3E4348', category:'finance',   label:'square'           },
  { id:87,  name:'Coinbase',        icon:'◎', color:'#0052FF', category:'finance',   label:'coinbase'         },
  { id:88,  name:'Plaid',           icon:'▣', color:'#000000', category:'finance',   label:'plaid'            },
  { id:89,  name:'Braintree',       icon:'⬢', color:'#3A3A3A', category:'finance',   label:'braintree'        },
  { id:90,  name:'Adyen',           icon:'◕', color:'#0ABF53', category:'finance',   label:'adyen'            },

  // ── Productivity & Other ─────────────────────────────────────────────────
  { id:91,  name:'Google Workspace',icon:'◈', color:'#4285F4', category:'cloud',     label:'google-workspace' },
  { id:92,  name:'Dropbox',         icon:'◉', color:'#0061FF', category:'cloud',     label:'dropbox'          },
  { id:93,  name:'OneDrive',        icon:'◎', color:'#0078D4', category:'cloud',     label:'onedrive'         },
  { id:94,  name:'Twilio',          icon:'⊕', color:'#F22F46', category:'developer', label:'twilio'           },
  { id:95,  name:'SendGrid',        icon:'▣', color:'#1A82E2', category:'developer', label:'sendgrid'         },
  { id:96,  name:'Mailchimp',       icon:'⬢', color:'#FFE01B', category:'developer', label:'mailchimp'        },
  { id:97,  name:'Intercom',        icon:'◕', color:'#1F8DED', category:'developer', label:'intercom'         },
  { id:98,  name:'Zendesk',         icon:'⬡', color:'#03363D', category:'developer', label:'zendesk'          },
  { id:99,  name:'HubSpot',         icon:'◧', color:'#FF7A59', category:'developer', label:'hubspot'          },
  { id:100, name:'Salesforce',      icon:'◈', color:'#00A1E0', category:'cloud',     label:'salesforce'       },
];
